[package]
name = "alea-ffi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
thiserror.workspace = true

[build-dependencies]
cc.workspace = true

[dev-dependencies]
allocation-counter.workspace = true
