[package]
name = "kernels"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
memory.workspace = true
rand.workspace = true
faer = { workspace = true, optional = true }
cblas = { workspace = true, optional = true }
ffi.workspace = true
thiserror.workspace = true
once_cell.workspace = true

[build-dependencies]
cc = { workspace = true, optional = true }
pkg-config = { workspace = true, optional = true }

[dev-dependencies]
approx.workspace = true
allocation-counter.workspace = true
criterion.workspace = true
pprof.workspace = true

[features]
default = []
simd = []
branch-hints = []
openblas = ["dep:cblas", "dep:cc", "dep:pkg-config"]
faer = ["dep:faer"]
std-autodiff = []
parallel = []

[[bench]]
name = "wiener7"
harness = false
