//! Executed BlackJAX references, not outputs generated by the Rust integrator.
//! Regeneration/provenance: docs/blackjax-reference.md.

use super::*;
use alea_math::metric::{CholeskyFactor, DenseMetric, DiagonalMetric, IdentityMetric};
use std::collections::BTreeSet;
#[path = "../../tests/support/targets.rs"]
mod targets;
use targets::Target;

const FIXTURES: &str = include_str!("../../tests/fixtures/blackjax-1.5.csv");
const M3_FIXTURES: &str = include_str!("../../tests/fixtures/blackjax-m3.csv");
const HEADER: &str = "target,mass,step_size,steps,l00,l10,l11,inverse00,inverse01,inverse11,q0,q1,p0,p1,logp,g0,g1,energy,end_q0,end_q1,end_p0,end_p1,end_logp,end_g0,end_g1,end_energy";

#[derive(Debug)]
struct Fixture<'a> {
    target: Target,
    mass: &'a str,
    step_size: f64,
    steps: usize,
    lower: [f64; 3],
    inverse: [f64; 3],
    // q[2], p[2], logp, gradient[2], Hamiltonian.
    initial: [f64; 8],
    endpoint: [f64; 8],
}

fn fixtures() -> Vec<Fixture<'static>> {
    let mut lines = FIXTURES.lines().filter(|line| !line.starts_with('#'));
    assert_eq!(lines.next(), Some(HEADER));
    let mut more = M3_FIXTURES.lines().filter(|line| !line.starts_with('#'));
    assert_eq!(more.next(), Some(HEADER));
    let rows: Vec<_> = lines
        .chain(more)
        .map(|line| {
            let fields: Vec<_> = line.split(',').collect();
            assert_eq!(fields.len(), 26, "malformed reference row: {line}");
            let numbers: Vec<f64> = fields[4..]
                .iter()
                .map(|field| field.parse().expect("fixture number"))
                .collect();
            assert!(numbers.iter().all(|value| value.is_finite()));
            assert!(matches!(fields[1], "identity" | "diagonal" | "dense"));
            Fixture {
                target: Target::parse(fields[0]),
                mass: fields[1],
                step_size: fields[2].parse().unwrap(),
                steps: fields[3].parse().unwrap(),
                lower: numbers[0..3].try_into().unwrap(),
                inverse: numbers[3..6].try_into().unwrap(),
                initial: numbers[6..14].try_into().unwrap(),
                endpoint: numbers[14..22].try_into().unwrap(),
            }
        })
        .collect();
    assert_eq!(
        rows.len(),
        90,
        "reference coverage must not silently shrink"
    );
    rows
}

fn buffer(values: &[f64]) -> OwnedBuffer {
    OwnedBuffer::from_fn(values.len(), |i| values[i])
}

fn close(actual: f64, expected: f64, field: &str, fixture: &Fixture<'_>) {
    // Mixed absolute/relative tolerance covers reordered f64 arithmetic in JAX
    // and scalar/SIMD/Faer/BLAS. This is not a statistical tolerance.
    let tolerance = 2e-12 * (1.0 + expected.abs());
    assert!(
        actual.is_finite() && (actual - expected).abs() <= tolerance,
        "{field}: actual={actual:.17e}, expected={expected:.17e}; {fixture:?}"
    );
}

fn check_state<M: EuclideanMetric>(
    phase: &mut Phase<'_, '_, Target, M>,
    expected: &[f64; 8],
    fixture: &Fixture<'_>,
) {
    let point = &phase.workspace.point;
    let actual = [
        point.position()[0],
        point.position()[1],
        phase.workspace.momentum[0],
        phase.workspace.momentum[1],
        point.log_density(),
        point.gradient()[0],
        point.gradient()[1],
        phase.energy().unwrap(),
    ];
    for ((value, reference), name) in actual
        .iter()
        .zip(expected)
        .zip(["q0", "q1", "p0", "p1", "logp", "g0", "g1", "energy"])
    {
        close(*value, *reference, name, fixture);
    }
}

fn check_mass<M: EuclideanMetric>(name: &str, metric: impl Fn(&Fixture<'_>) -> M) {
    let mut coverage = BTreeSet::new();
    for fixture in fixtures().iter().filter(|fixture| fixture.mass == name) {
        // Exact comparisons here validate discrete fixture configuration, not
        // computed floating-point results. Require both signs and every length.
        let expected_step = if fixture.target == Target::Rotated {
            0.000625
        } else {
            0.125
        };
        assert_eq!(fixture.step_size.abs(), expected_step);
        assert!(matches!(fixture.steps, 1 | 5 | 11));
        assert!(coverage.insert((fixture.target, fixture.step_size > 0.0, fixture.steps)));
        let metric = metric(fixture);
        for (basis, expected) in [
            ([1.0, 0.0], [fixture.inverse[0], fixture.inverse[1]]),
            ([0.0, 1.0], [fixture.inverse[1], fixture.inverse[2]]),
        ] {
            let mut velocity = [0.0; 2];
            metric.velocity(&basis, &mut velocity).unwrap();
            for (actual, reference) in velocity.into_iter().zip(expected) {
                close(actual, reference, "inverse mass", fixture);
            }
        }

        let live = PointState::new(&fixture.target, buffer(&fixture.initial[..2])).unwrap();
        let mut workspace = PhaseWorkspace::new(&live);
        let mut phase = workspace
            .start_with_momentum(&live, &metric, &fixture.initial[2..4])
            .unwrap();
        check_state(&mut phase, &fixture.initial, fixture);
        let forward = SignedStep::new(fixture.step_size).unwrap();
        for _ in 0..fixture.steps {
            phase = phase.step(forward).unwrap();
        }
        check_state(&mut phase, &fixture.endpoint, fixture);

        // Reverse from the actual Rust endpoint, retaining its cached gradient.
        let reverse = SignedStep::new(-fixture.step_size).unwrap();
        for _ in 0..fixture.steps {
            phase = phase.step(reverse).unwrap();
        }
        check_state(&mut phase, &fixture.initial, fixture);
        // These are deliberate exact comparisons: evolution must not touch live.
        assert_eq!(live.position(), &fixture.initial[..2]);
    }
    assert_eq!(
        coverage.len(),
        30,
        "missing {name} reference configurations"
    );
}

#[test]
fn blackjax_identity_endpoints_and_signed_reversal_agree() {
    check_mass("identity", |fixture| {
        assert_eq!(fixture.lower, [1.0, 0.0, 1.0]);
        IdentityMetric::new(2)
    });
}

#[test]
fn blackjax_diagonal_endpoints_and_signed_reversal_agree() {
    check_mass("diagonal", |fixture| {
        let [a, off_diagonal, b] = fixture.lower;
        assert_eq!(off_diagonal, 0.0);
        DiagonalMetric::new(buffer(&[a * a, b * b])).unwrap()
    });
}

#[test]
fn blackjax_dense_endpoints_and_signed_reversal_agree() {
    check_mass("dense", |fixture| {
        let [a, b, c] = fixture.lower;
        // Alea takes L in column-major order, with M = L L^T.
        DenseMetric::new(CholeskyFactor::new_lower(2, buffer(&[a, b, 0.0, c])).unwrap())
    });
}

fn energy_order<M: EuclideanMetric>(target: Target, metric: M) {
    let live = PointState::new(&target, buffer(&[0.7, -0.4])).unwrap();
    let mut workspace = PhaseWorkspace::new(&live);
    let duration = if target == Target::Rotated { 0.01 } else { 0.5 };
    let mut errors = [0.0; 3];
    for (level, count) in [32, 64, 128].into_iter().enumerate() {
        let mut phase = workspace
            .start_with_momentum(&live, &metric, &[0.3, 1.1])
            .unwrap();
        let initial = phase.energy().unwrap();
        let step = SignedStep::new(duration / count as f64).unwrap();
        for _ in 0..count {
            phase = phase.step(step).unwrap();
        }
        errors[level] = (phase.energy().unwrap() - initial).abs();
    }
    for pair in errors.windows(2) {
        let ratio = pair[0] / pair[1];
        assert!(
            (3.7..4.3).contains(&ratio),
            "{target:?}: {errors:?}, ratio={ratio}"
        );
    }
}

#[test]
#[cfg_attr(
    miri,
    ignore = "long convergence sweep; reference endpoints run under Miri"
)]
fn all_target_metric_pairs_have_second_order_energy_error() {
    for target in [
        Target::Correlated,
        Target::Banana,
        Target::Logistic,
        Target::Funnel,
        Target::Rotated,
    ] {
        energy_order(target, IdentityMetric::new(2));
        energy_order(target, DiagonalMetric::new(buffer(&[4.0, 0.25])).unwrap());
        energy_order(
            target,
            DenseMetric::new(CholeskyFactor::new_lower(2, buffer(&[1.5, 0.4, 0.0, 0.8])).unwrap()),
        );
    }
}
